// flow-typed signature: 3443ece59cdadee2295633dc26b3dbbc
// flow-typed version: <<STUB>>/feathers-authentication-client_v^0.3.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'feathers-authentication-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'feathers-authentication-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'feathers-authentication-client/example/app' {
  declare module.exports: any;
}

declare module 'feathers-authentication-client/example/primus-client' {
  declare module.exports: any;
}

declare module 'feathers-authentication-client/example/rest-client' {
  declare module.exports: any;
}

declare module 'feathers-authentication-client/example/socketio-client' {
  declare module.exports: any;
}

declare module 'feathers-authentication-client/lib/hooks/index' {
  declare module.exports: any;
}

declare module 'feathers-authentication-client/lib/hooks/populate-access-token' {
  declare module.exports: any;
}

declare module 'feathers-authentication-client/lib/hooks/populate-entity' {
  declare module.exports: any;
}

declare module 'feathers-authentication-client/lib/hooks/populate-header' {
  declare module.exports: any;
}

declare module 'feathers-authentication-client/lib/index' {
  declare module.exports: any;
}

declare module 'feathers-authentication-client/lib/passport' {
  declare module.exports: any;
}

declare module 'feathers-authentication-client/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'feathers-authentication-client/example/app.js' {
  declare module.exports: $Exports<'feathers-authentication-client/example/app'>;
}
declare module 'feathers-authentication-client/example/primus-client.js' {
  declare module.exports: $Exports<'feathers-authentication-client/example/primus-client'>;
}
declare module 'feathers-authentication-client/example/rest-client.js' {
  declare module.exports: $Exports<'feathers-authentication-client/example/rest-client'>;
}
declare module 'feathers-authentication-client/example/socketio-client.js' {
  declare module.exports: $Exports<'feathers-authentication-client/example/socketio-client'>;
}
declare module 'feathers-authentication-client/lib/hooks/index.js' {
  declare module.exports: $Exports<'feathers-authentication-client/lib/hooks/index'>;
}
declare module 'feathers-authentication-client/lib/hooks/populate-access-token.js' {
  declare module.exports: $Exports<'feathers-authentication-client/lib/hooks/populate-access-token'>;
}
declare module 'feathers-authentication-client/lib/hooks/populate-entity.js' {
  declare module.exports: $Exports<'feathers-authentication-client/lib/hooks/populate-entity'>;
}
declare module 'feathers-authentication-client/lib/hooks/populate-header.js' {
  declare module.exports: $Exports<'feathers-authentication-client/lib/hooks/populate-header'>;
}
declare module 'feathers-authentication-client/lib/index.js' {
  declare module.exports: $Exports<'feathers-authentication-client/lib/index'>;
}
declare module 'feathers-authentication-client/lib/passport.js' {
  declare module.exports: $Exports<'feathers-authentication-client/lib/passport'>;
}
declare module 'feathers-authentication-client/lib/utils.js' {
  declare module.exports: $Exports<'feathers-authentication-client/lib/utils'>;
}
