// flow-typed signature: 7534730dd1a4158dbee0984220dcf842
// flow-typed version: <<STUB>>/react-native-loading-spinner-overlay_v^0.5.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-loading-spinner-overlay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-loading-spinner-overlay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-loading-spinner-overlay/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-loading-spinner-overlay/src/index.js' {
  declare module.exports: $Exports<'react-native-loading-spinner-overlay/src/index'>;
}
